### ISSUE TITLE
v2 - Conditional refinement lists

### ISSUE THREAD

**Issue by pix2D** [algolia/vue-instantsearch#624] opened 2019-02-16 21:32 UTC
**Feedback on the v2 alpha version 🆕**

### Describe the bug / features

Would appreciate some help with this, I'm not sure if I'm doing anything wrong or if this is intended behavior.

We have around half a dozen facets at the moment with more to come. Due to this, the UI we chose is having refinement lists hidden behind a button representing each facet. When the button is clicked, the refinement list shows below the button (think like a dropdown menu). Clicking on the button again closes the list (same as clicking anywhere outside the "box").

There are 2 main issues with this in v2:

1) Since there is no searchStore anymore, it is not possible to get easy access to `_helper.state.disjunctiveFacetsRefinements` or `_helper.state.numericRefinements`. We need this in order to "detect" if a refinement list is "active" (thus changing the button styling indicating it as active).

2) When the refinement list is hidden (we use v-show to control visibility) any enabled refinements get removed automatically.

On a related note since there is no more searchStore now there is also no more `toggleFacetRefinement` method. What is the recommended approach to use instead now?

### How to resolve or implement the fix?

- Do not remove active refinements when a refinement list is hidden

- Add `disjunctiveFacetsRefinements` and `numericRefinements` (we only use these 2, not sure if there are any others that make sense) to the `ais-state-results` component so they can be used for conditional styling

- It would also be nice if there was a `isActive` property or something similar in the `ais-state-results` component (basically a boolean indicating where any part of Algolia is active; a query is present, or a refinement etc), though if the above is implemented this is simple enough to do on our own

### What is the version you are using?

 v2.0.0-beta.3

**Comment by Haroenv** [comment] 2019-02-18 09:55
* `v-show` shouldn't remove a refinement. `v-if` definitely does however. Can you give a sandbox of what's going on here, so it can be debugged?

* That's a great point, I thought this was already the case. You can read it from `state.disjunctiveFacets` for example. Here's one with hierarchical shown:

https://codesandbox.io/s/8kpw4qnjl

* this is something we plan to add to the `ais-panel` widget. For now it has access to `noRefinement`; `isRefined` was the next thing we were going to add.

>On a related note since there is no more searchStore now there is also no more `toggleFacetRefinement` method. What is the recommended approach to use instead now?

This would be ideally done with a `connectRefinementList` custom widget and call `this.state.refine` there in the correct part of the life cycle. Alternatively you can also use `connector: true` and then use `instantSearchInstance.helper` for low-level methods as you used before.

Thanks for all your feedback!

**Comment by tcmorris** [comment] 2019-02-28 18:58
I've managed to get the same behaviour as @pix2D when using the `sort-by` property of `ais-refinement-list`. 

e.g. if a sort by is provided such as `:sort-by="['isRefined', 'name:asc']"` to ensure the refinements are listed alphabetically, whenever I toggle the refinement list to hide it, the current refinements for that list get cleared. I'm using `v-show` to do the toggle so in theory all that it should be doing is setting the display property.

If I take out the `sort-by` override and just let it do the default, the refinements do stay in place.

**Comment by samouss** [comment] 2019-02-28 21:22
Hi @tcmorris, the issue you described might be linked to this one: https://github.com/algolia/vue-instantsearch/issues/575. Could you avoid to inline the `sort-by` attribute? You can store the value on the instance, it should solve the issue.

**Comment by tcmorris** [comment] 2019-03-01 09:52
Ah right ok, yeah makes sense and that works now. Cheers @samouss

**Comment by tcmorris** [comment] 2019-03-01 09:57
Cheers @samouss that seems to do the trick!

**Comment by alexbudure** [comment] 2019-03-01 21:17
@Haroenv is it possible to toggle that functionality off for v-if? I'm currently using https://github.com/euvl/vue-js-modal and they use v-if so every time I close the modal, I lose the filter

**Comment by pix2D** [comment] 2019-05-06 04:29
Just wanted to report back that not inlining `:sort-by` per @samouss fixed the second issue. And a custom connector gets access to the underlying helper like before. Cheers.

**Comment by Haroenv** [comment] 2019-05-08 14:32
Whether a facet is active will be in `disjunctiveFacetsRefinements`

**Comment by Haroenv** [comment] 2019-05-08 14:32
The refinements are available in `state.disjunctiveFacetsRefinements`.

**Comment by pix2D** [comment] 2019-05-11 09:15
@Haroenv Right, but this is not available through `<AisStateResults>`.

In any case I have finally solved all my issues now. I've created individual computed properties for each data point I need in my custom connector component (instead of having them all in 1 like in my example above), and I'm no longer trying to pass it up to the parent component via an event.

Now I just wrapped the whole contents of the parent component in the default slot of my connector component, and am passing in the computed props to the parent through the slot (like it's done with `<AisStateResults>`). The result is no more infinite event loops, and everything works. :tada:

**Comment by Haroenv** [comment] 2019-05-13 07:22
Makes sense, regarding no refinements showing, it's something we were working on in https://github.com/algolia/vue-instantsearch/pull/627, but put temporarily on hold because it would be a breaking change.

**Closed by Haroenv** 2019-05-13 07:22 UTC
Labels: Feedback

**Comment by pix2D** [comment] 2019-05-29 18:56
@Haroenv Any thoughts on @alexbudure comment above? I am now also at this same issue actually. I have filters in a modal, and anytime the modal is closed any filters set are undone.

**Comment by Haroenv** [comment] 2019-05-30 13:46
This is not something we can do with the way Vue is working, our refinements are solely based on the component tree. If you use v-if, that means the component won't be in the tree

**Comment by jessemarple** [comment] 2019-06-20 21:28
I need the ```sort-by``` property. I don't understand why there needs to be some javascript gymnastics to keep the values of the existing fasts when hiding the refinement lists.

How on earth are we to design/developer complicated, multifaceted, UIs if we can't be allowed to hide refinement lists (and other components) without resetting the whole query?

**Comment by jessemarple** [comment] 2019-06-20 21:30
> Hi @tcmorris, the issue you described might be linked to this one: #575. Could you avoid to inline the `sort-by` attribute? You can store the value on the instance, it should solve the issue.

Is there any way to drop an example of this. The one mentioned in #575 does not seem to actually show how to 
>  "save" the attributes inside data to avoid this issue

**Comment by samouss** [comment] 2019-06-21 10:23
Here is how you can do it for the `sort-by` widget:

```vue
<template>
  <ais-instant-search [...]>
    <ais-sort-by :items="sortByItems" />
  </ais-instant-search>
</template>

<script>
export default {
  data() {
    return {
      // ...
      sortByItems: [
        { value: "instant_search", label: "Featured" },
        { value: "instant_search_price_asc", label: "Price asc." },
        { value: "instant_search_price_desc", label: "Price desc." }
      ]
    };
  }
};
</script>
```

You can find a live example on [CodeSandbox](https://codesandbox.io/s/vue-instantsearch-sortby-without-inline-items-mj5hu).

**Comment by jessemarple** [comment] 2019-06-21 14:17
@samouss - that doesn't solve the sorting of the **refinement lists** as per the original issue. That's a sort of the items.

> having refinement lists hidden behind a button representing each facet

The solution I've come to is to use :transform-items and then a function to return the items in the order I need them to do in. 

`
              <ais-refinement-list
                attribute="departments"
                :transform-items="alphabetizeItems"
              ></ais-refinement-list>
...

    alphabetizeItems(items) {
      return _.sortBy(items, ["label"]);
    }
`

**Comment by tcmorris** [comment] 2019-06-24 09:15
@jessemarple nice that you got a working approach. fyi, in the docs it mentions to define a string array of what to sort your refinement list by:
https://www.algolia.com/doc/api-reference/widgets/refinement-list/js/#widget-param-sortby

This is what I'm using to sort alphabetically: `sortBy: ["isRefined", "name:asc"]`

**Comment by samouss** [comment] 2019-06-24 10:38
@jessemarple My bad for the misunderstanding, I thought the problem was related to the inlined value of the `sort-by` prop. Not about how to apply sort on the `ais-refinement-list`. 

Glad to see that you've solved your issue though! Like @tcmorris said we support the [`sort-by`](https://www.algolia.com/doc/api-reference/widgets/refinement-list/vue/#widget-param-sort-by) option with pre-defined tokens to allow a "simple" sort. The solution you came up with is more appropriate when none of our pre-defined sorts apply.

Note that the current thread is related to "Conditional refinement" not about "How to sort a refinement list". Next time don't hesitate to open a new issue otherwise the context and the main purpose of the issue is lost. Thanks!

**Comment by Liliane97** [comment] 2022-12-22 23:43
Goodnight. I'm having difficulty with the ais-refinement-list. The problem I'm having is that when I select one of the options the other options disappear, how do I make sure that when I click on one the other options don't disappear? Like being able to select more than one?

**Comment by Haroenv** [comment] 2022-12-23 10:14
That should be the default behaviour @Liliane97, please open an issue with reproduction and we'll have a look :)

**Comment by Liliane97** [comment] 2022-12-23 12:01
I wanted it to have this behavior, I've already analyzed Algolia's example codes that use it.... maybe I'm doing something wrong. The functionality of showing items related to it works, the question is just that when I select an option the others disappear and appear when I uncheck them.
[](url)
[Gravação de tela de 23-12-2022 08:56:07.webm](https://user-images.githubusercontent.com/62839968/209332465-32c5cd88-3e6c-45d7-a00b-8860d26fefe3.webm)
