### ISSUE TITLE
Filters prop on ais-configure is not applied dynamically from version 2.0.0 and higher

### ISSUE THREAD

**Issue by fomalhaut79** [algolia/vue-instantsearch#653] opened 2019-03-29 02:55 UTC
**Bug 🐞**

In my project I need to apply some filters dynamically. It worked fine in beta versions of Vue-instantsearch 2.
You can see the difference here: https://codesandbox.io/s/xpqqz4rlkz
If we downgrade dependency version of Vue-instantsearch (2.0.1 => 2.0.0-beta3) the filter prop on ais-configure works as expected.

**Comment by Haroenv** [comment] 2019-03-29 08:56
This is very surprising, Configure hasn't changed since `2.0.0-alpha.3`. I'm trying it out to see if I can replicate it

**Comment by Haroenv** [comment] 2019-03-29 08:58
I tried it out, and both behave exactly identical. Can you make a gif showing the difference please?

**Comment by Skullbock** [comment] 2019-06-17 16:08
Hi @Haroenv i'm facing the same issue.
here's the code:

```
<ais-configure
                        :disjunctive-facets-refinements.camel="{ ...defaultGemstoneFilters }"
                >
                    <div slot-scope="{ searchParameters}">
                        <pre>{{ searchParameters }}</pre>
                    </div>
                </ais-configure>
```

and the screenshots

<img width="1051" alt="Schermata 2019-06-17 alle 18 06 37" src="https://user-images.githubusercontent.com/1104083/59619419-c1f19600-912a-11e9-8f33-6ee02ebb260e.png">
<img width="410" alt="Schermata 2019-06-17 alle 18 06 07" src="https://user-images.githubusercontent.com/1104083/59619424-c28a2c80-912a-11e9-8157-8fb9fa20c1f4.png">

As you can see, the `AisConfigure` Widget properly receives the mutated prop, while the `searchParameters` data is not changed, and therefore the new search is not triggered.

Any thoughts?

**Comment by Haroenv** [comment] 2019-06-24 09:04
Can you create what you have so far in a sandbox environment? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/vue-instantsearch). Thanks!

**Comment by Skullbock** [comment] 2019-06-24 09:28
I think i managed to solve it (still don't know how)
I reproduced it (in a very simplified way) here and it works as expected.

https://codesandbox.io/s/vue-instantsearch-app-t9dyk

I'll try to debug it further to understand what changed, but in the meantime i think we can close this one :)

Sorry for the trouble

**Comment by Haroenv** [comment] 2019-06-24 09:36
no problem, sorry for the delay

**Closed** 2019-06-24 09:36 UTC
