### ISSUE TITLE
Tree Menu laravel category

### ISSUE THREAD

**Issue by zymawy** [algolia/vue-instantsearch#475] opened 2018-08-07 03:09 UTC
Hi Coder,

Thank You For This Cool Components.  
I'm Trying To Accomplish Category And SubCactegory Tree Menu With Laravel.
I want Import It From Laravel Like This 
```json
{
  "objectID": "123",
  "name": "orange",
  "categories": {
    "lvl0": "fruits",
    "lvl1": "fruits > citrus"
  }
}
```
> So That I Can Use it Like This [Example](https://community.algolia.com/vue-instantsearch/examples/bootstrap.html)

In My Project, I have Category Table And This Is The Structure Of The Table 

```php
        Schema::create('categories', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('category_id')->unsigned()->nullable(); // The Perent Id If It's Sub Category
            $table->string('name', 60);
            $table->string('description', 100);
            $table->string('icon', 60)->nullable();
            $table->string('image', 100)->nullable();
            $table->boolean('status')->default(1);
            $table->enum('type', ['group', 'store'])->default('store');

            $table->foreign('category_id')->references('id')->on('categories');

            $table->timestamps();
        });
```

And On My `Product` Model 

```php
    public function toSearchableArray()
    {
        /**
         * Load the categories relation so that it's available
         *  in the laravel toArray method
         */
        $array = $this->toArray();

        if($this->category->whereNull('category_id')) 
        {
            $array['category'] = [
                'name' => $this->category->name,
                
            ];
        }
        

        if ($this->category->children()->exists()) {

            $array['sub_categories'] = $this->category->children()->map(function ($data) {
                return [
                    'name' => $data['name'],
                ];
            });
        }

        return $array;
    }
```
How I Can Achive That.
Thank You For Everything.

**Comment by julienbourdeau** [comment] 2018-08-07 08:04
Hi @zymawy, can you paste here what the array look like in the end?

To explain what you need to do, I think you should get something close to this:

```php
  public function toSearchableArray()
  {
      $array = $this->toArray();
      $mainCategoryName = $this->category->name;

      $array['category'] = [
          'lvl0' => $mainCategoryName,
      ];

      if ($this->category->children()->exists()) {
          $array['category']['lvl1'] = [];
          foreach ($this->category->children() as $cat) {
              $array['category']['lvl1'][] = "$mainCategoryName > ".$cat['name'];
          }
      }

      return $array;
  }
```
Note: the code is not tested, it's just an example to illustrate what you have to do here.

I'll close the issue for now as it's not a bug but please, let me know if that worked!

**Closed** 2018-08-07 08:04 UTC
Labels: Support
