### ISSUE TITLE
Routing only on parameters.

### ISSUE THREAD

**Issue by bootsmann1995** [algolia/vue-instantsearch#930] opened 2021-03-15 12:07 UTC
Hello Algolia

When I use this libary I have an issue with routing in my nuxt solution. 

I have a page like this: domain.com/my-path?param1=bla&param2=bla

And on this page I have link like this:  domain.com/my-path?newParam=bla&newParam2=bla

When I press this link. Only the params are changed but it does not "count" as a pagechange. This does so my search results are not updated. Do you have a fix for this?.

Thank you
- Anders Bootsmann

**Comment by Haroenv** [comment] 2021-03-15 12:34
Do you have a sandbox which shows this behaviour? Is this a html anchor or a vue router link? How is `routing` implemented in your application? 

Thanks!

**Comment by bootsmann1995** [comment] 2021-03-15 12:59
Sorry i don't have a sandbox but it is vue router-link and routing is implemented like this: 

vue component:

```
 data() {
        // Created in `data` to access the Vue Router
        const mixin = createServerRootMixin({
            searchClient: getSearchClient(),
            indexName: process.env.indice,
            replicas: [
                `SortByDESC ${process.env.commerceCulture}`,
                `SortByASC ${process.env.commerceCulture}`,
                `SortByLaunch ${process.env.commerceCulture}`,
                `SortByDiscountDESC ${process.env.commerceCulture}`
            ],
            routing: {
                router: nuxtRouter(this.$nuxt.$router),
                stateMapping: singleIndex(process.env.indice)
            }
        });
        return {
            ...mixin.data()
        };
    },
   
 ````
 
 
nuxt router: 

```
export function nuxtRouter(vueRouter: any) {
  let writeTimer: any;
  return {
    read() {
      return vueRouter.currentRoute.query;
    },
    write(routeState: any) {
      writeTimer = setTimeout(
        () =>
          vueRouter.push({
            query: routeState,
          }),
        400
      );
    },
    createURL(routeState: any) {
      return vueRouter.resolve({
        query: routeState,
      }).href;
    },
    onUpdate(cb: any) {
      (this as any)._onPopState = ({ state }: {state: any}) => {
        if (writeTimer) {
          clearTimeout(writeTimer);
        }
        const routeState = state;
        // at initial load, the state is read from the URL without
        // update. Therefore the state object is not there. In this
        // case we fallback and read the URL.
        if (!routeState) {
          cb(this.read());
        } else {
          cb(routeState);
        }
      };
      window.addEventListener("popstate", (this as any)._onPopState);
    },
    dispose() {
      window.removeEventListener("popstate", (this as any)._onPopState);

      if (writeTimer) {
        clearTimeout(writeTimer);
      }
    },
  };
}
```

**Comment by bootsmann1995** [comment] 2021-03-17 09:24
@Haroenv

**Comment by eunjae-lee** [comment] 2021-03-18 16:08
@Haroenv this seems to be similar to another issue I tackled today. In the earlier case, the goal was to remove all the refinements, but here it's to apply new ones. I'm not sure what is a good workaround here.

**Comment by Haroenv** [comment] 2021-03-18 16:30
I don't have a solution now, but I think it's related to the fact that this router isn't listening to changes in Vue Router in the onUpdate. You can listen to router.afterEach in onUpdate and call `cb` using this.read: https://router.vuejs.org/guide/advanced/navigation-guards.html#global-after-hooks

**Comment by bootsmann1995** [comment] 2021-03-19 07:55
@Haroenv  thank you for the answer! 
Do you have an example of this? if not, can you show me some how?

**Comment by Haroenv** [comment] 2021-03-19 09:28
```ts
import VueRouter from 'vue-router';

type RouteState = { [key: string]: any };

export function nuxtRouter(vueRouter: VueRouter) {
  let writeTimer: ReturnType<typeof setTimeout> | null = null;
  let onPopState: (ev: PopStateEvent) => any | undefined;
  return {
    read() {
      return vueRouter.currentRoute.query;
    },
    write(routeState: RouteState) {
      writeTimer = setTimeout(
        () =>
          vueRouter.push({
            query: routeState,
          }),
        400
      );
    },
    createURL(routeState: RouteState) {
      return vueRouter.resolve({
        query: routeState,
      }).href;
    },
    onUpdate(cb: (routeState: RouteState) => void) {
      vueRouter.afterEach(() => {
        cb(this.read());
      });

      if (typeof window === 'object') {
        onPopState = () => {
          if (writeTimer) {
            clearTimeout(writeTimer);
          }

          cb(this.read());
        };
        window.addEventListener('popstate', onPopState);
      }
    },
    dispose() {
      if (writeTimer) {
        clearTimeout(writeTimer);
      }

      if (typeof window === 'object') {
        window.removeEventListener('popstate', onPopState);
      }
    },
  };
}
```

this should work, although I don't have a vue router example ready now to try it with @bootsmann1995

**Comment by bootsmann1995** [comment] 2021-03-24 13:55
Hey @Haroenv 

This works :) but when i press a link it keeps routing between the two links in a loop :)

**Comment by Haroenv** [comment] 2021-03-24 14:45
inside write you probably want to cancel the previous timeout as well, that should fix it I think @bootsmann1995

**Comment by bootsmann1995** [comment] 2021-03-24 14:56
so you just want to remove write? or just the timeout wrapper?

**Comment by bootsmann1995** [comment] 2021-03-24 14:57
or do you want this? clearTimeout(writeTimer);

**Comment by bootsmann1995** [comment] 2021-04-13 11:36
``` write(routeState: RouteState) {
      writeTimer = setTimeout(
        () => {
          vueRouter.push({
            query: routeState,
          })

          if (writeTimer) {
            clearTimeout(writeTimer);
          }
        },
        400
      );
      
    },```
This is not working :) still keeps changeing between the routes.

**Comment by bootsmann1995** [comment] 2021-04-20 06:50
@Haroenv

**Comment by Haroenv** [comment] 2021-04-20 07:51
I see there's no check that the route to write is different to the one already written, could you add that?

**Comment by bootsmann1995** [comment] 2021-04-27 07:43
But how would you do that? :) bc i would be different every time, it switches between the two routes

**Comment by bootsmann1995** [comment] 2021-04-27 07:53
like this? @Haroenv 
```
write(routeState: RouteState) {
      writeTimer = setTimeout( () =>{
          vueRouter.push({
            query: routeState,
          })
          
        }, 400
      );
      if(routeState !== vueRouter.currentRoute.query && writeTimer) {
        clearTimeout(writeTimer);
      }
    }, 
   
```

**Comment by Haroenv** [comment] 2021-04-27 08:11
```ts
import VueRouter from 'vue-router';
import isEqual from 'lodash/isEqual';

type RouteState = { [key: string]: any };

export function nuxtRouter(vueRouter: VueRouter) {
  let writeTimer: ReturnType<typeof setTimeout> | null = null;
  let onPopState: (ev: PopStateEvent) => any | undefined;
  return {
    read() {
      return vueRouter.currentRoute.query;
    },
    write(routeState: RouteState) {
      writeTimer = setTimeout(() => {
        // don't write identical urls
        if (!isEqual(this.read(), routeState)) {
          vueRouter.push({
            query: routeState,
          });
        }
      }, 400);
    },
    createURL(routeState: RouteState) {
      return vueRouter.resolve({
        query: routeState,
      }).href;
    },
    onUpdate(cb: (routeState: RouteState) => void) {
      vueRouter.afterEach(() => {
        // clear timer if there's a new URL
        if (writeTimer) {
          clearTimeout(writeTimer);
        }

        cb(this.read());
      });

      if (typeof window === 'object') {
        onPopState = () => {
          // clear timer if there's a new URL
          if (writeTimer) {
            clearTimeout(writeTimer);
          }

          cb(this.read());
        };
        window.addEventListener('popstate', onPopState);
      }
    },
    dispose() {
      if (writeTimer) {
        clearTimeout(writeTimer);
      }

      if (typeof window === 'object') {
        window.removeEventListener('popstate', onPopState);
      }
    },
  };
}
```

I just noticed there's no clearing of the write timer in on update, this should help @bootsmann1995

**Comment by bootsmann1995** [comment] 2021-04-27 08:14
It still switches between in a loop :D @Haroenv

**Comment by bootsmann1995** [comment] 2021-04-27 08:15
this actually works in local: 

```
import VueRouter from 'vue-router';

type RouteState = { [key: string]: any };

export function nuxtRouter(vueRouter: VueRouter) {
  let writeTimer: ReturnType<typeof setTimeout> | null = null;
  let onPopState: (ev: PopStateEvent) => any | undefined;
  return {
    read() {
      return vueRouter.currentRoute.query;
    },
    write(routeState: RouteState) {
      writeTimer = setTimeout( () =>{
          vueRouter.push({
            query: routeState,
          })
          
        }, 400
      );
      if(routeState == vueRouter.currentRoute.query && writeTimer) {
        clearTimeout(writeTimer);
      }
    },
    createURL(routeState: RouteState) {
      return vueRouter.resolve({
        query: routeState,
      }).href;
    },
    onUpdate(cb: (routeState: RouteState) => void) {
      vueRouter.afterEach(() => {
        cb(this.read());
      });

      if (typeof window === 'object') {
        onPopState = () => {
          if (writeTimer) {
            clearTimeout(writeTimer);
          }

          cb(this.read());
        };
        window.addEventListener('popstate', onPopState);
      }
    },
    dispose() {
      if (writeTimer) {
        clearTimeout(writeTimer);
      }

      if (typeof window === 'object') {
        window.removeEventListener('popstate', onPopState);
      }
    },
  };
} 
```

**Comment by Haroenv** [comment] 2021-04-27 08:21
Can you make a sandbox or repo with your exact setup please? I'm having a hard time coding "blindly" on this

**Comment by bootsmann1995** [comment] 2021-04-27 08:23
@Haroenv  would you have the time for at session on discord or something? bc it's a really big project.

**Comment by bootsmann1995** [comment] 2021-05-31 10:53
@Haroenv  Please link me the sanbox solutions you have with nuxt, and would be cool if they have the router implemented.

**Comment by bootsmann1995** [comment] 2021-06-03 07:57
@Haroenv

**Comment by Haroenv** [comment] 2021-06-03 09:53
can you contact support@algolia.com with a reproducible example instead? GitHub isn't the best place to keep track of conversations

**Comment by Haroenv** [comment] 2021-06-03 13:14
A clear description of exactly what's not working and reproduction on codesandbox yes, thanks!

**Comment by bootsmann1995** [comment] 2021-06-07 09:08
@Haroenv  Yes but what are your links to the working sandboxes? :)

**Comment by bootsmann1995** [comment] 2021-06-10 06:10
@Haroenv

**Comment by Haroenv** [comment] 2021-06-10 07:04
All working sandboxes are here: https://instantsearch-templates.netlify.app

**Comment by bootsmann1995** [comment] 2021-06-11 07:20
Hey @Haroenv  since this thread is about routing, can I ask why the router ads this to my url after load: 
![image](https://user-images.githubusercontent.com/65391517/121647085-46ffb380-ca96-11eb-81d8-3abd492a5da1.png)

**Comment by Haroenv** [comment] 2021-06-11 09:04
likely because you set a default sortBy that isn't the same as your index name

**Comment by bootsmann1995** [comment] 2021-06-11 11:27
is there a way to fix this, so it wont be applied to the url ? :)

**Comment by Haroenv** [comment] 2021-06-11 13:48
you can set the index name on the InstantSearch component to be the same as the default on sortBy

**Comment by bootsmann1995** [comment] 2021-06-13 13:53
It does not work :) and this is your sandbox: 
![image](https://user-images.githubusercontent.com/65391517/121810033-80374f80-cc5f-11eb-905a-19f722d1de56.png)

**Comment by Haroenv** [comment] 2021-06-14 07:16
That's a codesandbox issue, unrelated to the Vue InstantSearch code, because the sandbox is opened too many times at once. Is this problem something you can reproduce in a sandbox (you can download and upload a new one)?

**Comment by bootsmann1995** [comment] 2021-06-14 09:16
I can try :) but I also get this on some of my pages but not all pages: 
![image](https://user-images.githubusercontent.com/65391517/121868973-dceb4680-cd01-11eb-812c-05b4a1b3c815.png)

do you know something about this error? I only get it on the pages with algolia

**Comment by Haroenv** [comment] 2021-06-14 15:49
can you open individual issues _with reproduction_ instead of continuing to put unrelated things in this issue? It's impossible to follow where you are stuck this way. In general it's also a better idea to open support tickets, since those have multiple people on instead of just our team, which is meant for reproducible bug reports, not support requests.

I have no idea what case that error comes in, so a reproduction is *required* for helping.

Hope you understand. This thread is so wildly confusing that I don't think we can answer all the questions, so I'll close it. Please reopen focused issues or support requests (where relevant)

Thanks!

**Closed by Haroenv** 2021-06-14 15:49 UTC
