### ISSUE TITLE
[Docs] Note for User to Try "0.0.0.0

### ISSUE THREAD

**Issue by agdavid** [algolia/vue-instantsearch#468] opened 2018-07-05 16:15 UTC
**Do you want to request a *feature* or report a *bug*?**

**Bug: What is the current behavior?**

**Bug: What is the expected behavior?**

**Bug: What browsers are impacted? Which versions?**

**Bug: What is the proposed solution?**

**Feature: What is your use case for such a feature?**

**Feature: What is your proposed API entry? The new option to add? What is the behavior?**

**What is the version you are using? Always use the latest one before opening a bug issue.**

**Comment by samouss** [comment] 2018-07-05 16:33
Duplicate of https://github.com/algolia/vue-instantsearch/issues/469

**Closed by samouss** 2018-07-05 16:33 UTC
