### ISSUE TITLE
transform-items called multiple times

### ISSUE THREAD

**Issue by mategvo** [algolia/vue-instantsearch#707] opened 2019-07-30 13:38 UTC
**Bug 🐞**

### What is the current behavior?

`transform-items` called multiple times on `ais-infinite-hits`. For each `ais-refinement-list` component there will be another extra call made. In my case it's 12 calls, which makes the website glitchy. 

### Make a sandbox with the current behavior

https://codesandbox.io/s/vue-instantsearch-v2-starter-f7o8b?fontsize=14

### What is the expected behavior?

call `transoform-items` only once, after new hits are added. 

When the items are transformed vue refreshes item-template. In my case it's masonry layout with quite large images. So transform-items is too expensive to be called multiple times.

### Does this happen only in specific situations?

When changing filters (please click on a product title in sandbox to change optional filter brand name). Console will log when transform-items is called. 

### What is the proposed solution?

Call transform-items only once, when the hits are added.

### What is the version you are using?

vue-instantsearch ^2.3.0 (updated today)

**Comment by Haroenv** [comment] 2019-07-30 13:58
Hi @mateuszgwozdz, I don't see any superficial calls to transformItems, because when you add a filter, it's likely the result set will be different. If we would do a check to see if the elements are identical, it would likely be much slower than just calling the transformItems function on every change. 

However, are you describing it being called multiple times for a single refinement? I can't reproduce that for the demo you sent. Every change in parameters only calls transformItems once

**Comment by mateuszgwozdz** [comment] 2019-07-30 14:20
Have you clicked on a hit f.e. "Motorola - MOTO G (4th Generation) 4G LTE with 16GB Memory Cell Phone (Unlocked) - Black" on the right side of the intreface? The console output should be:

```
setting optional filters brand:Motorola 
transforming items 
transforming items 
transforming items 
transforming items 
transforming items 
transforming items 
```

and as you can see above, that'd be six `tranform-items` calls for a single filter change (I added more refinment components so you can better understand this is problematic)

**Comment by mateuszgwozdz** [comment] 2019-07-31 12:25
@Haroenv even more problematic is that results are requested multiple times as well. Upon inspection of network pane you will see this, for every click:

<img width="866" alt="Screenshot 2019-07-31 at 14 22 55" src="https://user-images.githubusercontent.com/7168481/62211500-f2218b00-b39e-11e9-92fe-3e7a8eb1fac2.png">

**Comment by Haroenv** [comment] 2019-07-31 13:25
The  multiple identical queries can be fixed by adding `algoliasearch(xxx, xxx, { _useRequestCache: true })`, but I still don't see how in that UI you are rerendering the page (any rerender will cause a request, maybe identical as an existing one if it hasn't finished yet)

**Comment by patkeav** [comment] 2020-03-31 16:02
I am noticing this issue too. Using `vue-instantsearch` 2.7.0. When using several refinements lists, the call to `transform-items` is happening multiple times. 
<img width="228" alt="Screen Shot 2020-03-31 at 9 59 26 AM" src="https://user-images.githubusercontent.com/6840035/78048179-94cb4880-7336-11ea-868e-cc7823865f95.png">

It looks to happen as many times as there are refinement lists, as we have 6. It is also calling it 6 additional times each time the results are refined. I've looked on the page and there is nothing re-rendering the component, this seems to be coming from algolia. 

Any movement on this?

**Comment by mateuszgwozdz** [comment] 2020-03-31 16:09
All you can do for now is to use `algoliasearch(xxx, xxx, { _useRequestCache: true })` to prevent multiple queries to be sent to algolia. I don't think re-rendering was/can be fixed

**Comment by Haroenv** [comment] 2020-03-31 18:10
Every refinement list gets its own transformation, it’ll get called many times because we need to know what the return value is to be able to use it correctly.  What wrong effects do you see in this being called?

If you’re using client v4, it already has request cache by default

**Comment by patkeav** [comment] 2020-03-31 22:16
We do dynamic pricing on our site which we call our own database for, we call the `transformItems` to get the full list of results from the query, then loop through each one and compare with our database. The call the transformItems gets called many times so it calls our database each time, which slows performance. 

I've tried setting _useRequestCache, but I'm getting another error when using it like so: 
`algoliasearch('applicationId', 'adminApiKey', { _useRequestCache: true });` 
```Object literal may only specify known properties, and '_useRequestCache' does not exist in type 'AlgoliaSearchOptions'.```

Is there perhaps another way to get the list of results outside of `transformItems`?

**Comment by Haroenv** [comment] 2020-04-01 07:42
Can you make this in a sandbox pleas @patkeav? I'm not sure how you are implementing this now :)

**Comment by Haroenv** [comment] 2022-12-21 15:44
This will not change any further, transformItems gets called as many times as needed to render

**Closed by Haroenv** 2022-12-21 15:44 UTC
