### ISSUE TITLE
"In" and "Not in" combined refinement

### ISSUE THREAD

**Issue by Finnepinnen** [algolia/vue-instantsearch#661] opened 2019-04-17 08:07 UTC
**Feature ⚡️**

### What is your use case for such a feature?
When searching for posts with tags, some tags could be interesting and some other not. It would therefore be interesting to have a widget that based on the tags either can include or exclude posts.

### What is your proposal
If the following index structure is available
**Models**
- News
-- Content
-- Tags
--- Tag

and a refinement filter based on Tags facet
Include                Exclude
X        Bicycle       _
_    Environment   _
_          Cars          X

Then a news with the following tag combination would be visible
Bicycle
Bicycle, Environment

But not
Cars
Environment, Cars
Bicycle, Cars

### What is the version you are using?
2.0

**Comment by Finnepinnen** [comment] 2019-04-17 11:22
When I try to do that, given that I have activated "Advanced Syntax", the refinement disappears from the facet list since the isExcluded property is not set to true in the response and the item is left out.

Does the refine("-" + value) call addFacetExclusion?

**Comment by Haroenv** [comment] 2019-04-17 11:29
No, it uses regular facetFilters, not exclusions. Could you make a sample of what you have so far?

**Comment by Finnepinnen** [comment] 2019-04-17 20:28
This is what I got and it is built with vuetify and it kinda works. The missing part is the "item.isExcluded" property.

```
<template>
  <!-- Refinement list with a transform that saves the initial collection of refinements -->
  <ais-refinement-list 
    :attribute="attribute"
    :sort-by="['name:asc']" 
    :transform-items="getStaticItems" 
    operator="and" 
    :limit="20"
  >
    <template slot-scope="{state, items, refine}">
        <v-flex v-for="item in items" :key="item.objectID" xs12>
          <v-checkbox
            :value="item.isRefined"
            @change="refine(item.value)"
          ></v-checkbox>
          {{item.value}}
          <v-checkbox 
            :value="item.isExcluded"
            @change="refine(item.nvalue)" 
          ></v-checkbox>
        </v-flex>
    </template>  
  </ais-refinement-list>
</template>

<script>
export default {
  name: "StaticFilter",
  props: {
    attribute: String,
    default: null,
  },

  data() {
    return {
      staticValues: []
    }
  },

  methods: {
    getStaticValues(items) {
      // If not initiated, return the values of the initial facet items list
      if(this.staticValues.length == 0)
        this.staticValues = items.map(item => item.value);

      return this.staticValues
    },
    getStaticItems(items) {
      // Get vector of static values
      const values = this.getStaticValues(items);

      // Map the items onto the item values/labels
      return values.map(value => {
        
        // Find the item among the items return from the recent refine
        const item = items.find(item => item.label === value);        
        
        // If the item is among the results return the item
        if (item) {
          return {
            ...item,
            nvalue: '-' + value,
            disabled: false,
          } 
        } 
        // Otherwise return a blank item
        else {
          return {
            label: value,
            value,
            count: 0,
            isRefined: false,
            highlighted: value,
            nvalue: '-' + value,
            disabled: true,
          }
        }
      });
    },
  }
}
</script>
```
a nice feature would be something like

```
<template slot-scope="{state, items, refine, exclude}">
...
  <v-checkbox
    :value="item.isRefined"
    @change="refine(item.value)"
  ></v-checkbox>
  <span>{{item.value}}</span>
  <v-checkbox 
    :value="item.isExcluded"
    @change="exclude(item.value)" 
  ></v-checkbox>
...
</template>
```

**Comment by Haroenv** [comment] 2019-04-18 08:27
So in this case, you have a UI that looks like a refinement-list, but instead has a checkbox on both sides? Do you have a screenshot of that? The reason we didn't go for this behaviour in core is because we couldn't find a sufficiently good look for this kind of behaviour, without being confusing.

Thanks for your feedback!

**Comment by Finnepinnen** [comment] 2019-04-18 10:48
Yes thats correct! And the no refinement occurs but rather disabling of the options.

https://www.dropbox.com/s/cszpt1243xp4ggj/static_refinement.png?dl=0

**Comment by Finnepinnen** [comment] 2019-04-18 14:22
Do you have an idea on how I can solve the isExluded property?

**Comment by Haroenv** [comment] 2019-04-18 14:24
Can you create what you have so far in a sandbox environment? We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/vue-instantsearch). Thanks!

I think you'll need to keep track of those in a separate list, but they might also show up as `isRefined`

**Comment by Finnepinnen** [comment] 2019-04-18 14:39
Cool! Yes here is the sandbox
https://codesandbox.io/s/m3z47x7xwj

Thanks for quick reply :)

**Comment by Haroenv** [comment] 2019-04-18 14:55
@Finnepinnen, that sandbox still looks like the default; did you save?

**Comment by Finnepinnen** [comment] 2019-04-18 16:49
> @Finnepinnen, that sandbox still looks like the default; did you save?

Forgot, now its saved!

**Comment by Finnepinnen** [comment] 2019-04-18 22:28
This seems to work though, reworked the the staticValues -> staticItems to incorporate isExcluded and disabled.

https://codesandbox.io/s/n7nrxxr0rl

**Comment by Haroenv** [comment] 2019-04-19 08:38
This looks good to me, thanks for sharing!

I'll close this issue now, but we definitely noted your use case in our backlog of ideas.

**Closed by Haroenv** 2019-04-19 08:38 UTC
Labels: Feedback

**Comment by pix2D** [comment] 2019-10-08 06:38
@Haroenv I am trying to implement something similar as described here, but in a "slightly" more complex fashion. I want to combine inclusions and exclusions simultaneously. To further complicate things, the inclusions and exclusions should have a `and` relationship between them but an `or` within.

So something like:

from facet X: (include A or B or C) AND (exclude D or E)

Item 1 that has values B, C, F would be included
Item 2 that has values A, D would be excluded
Item 3 that has values D, F would be excluded
etc.

Is something like this feasible through a custom refinement list? If not, any thoughts on what approach I should take to implement this in a fully custom fashion?

**Comment by Haroenv** [comment] 2019-10-08 07:44
This sounds like it would fit best as a custom list which only does excludes (you can use the algoliasearch-helper functions for this as described), and a separate list which only does disjunction like the regular refinement-list. To be able to help you more, It'd be ideal if you'd open an issue with a template on how far you have gotten by now. We have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/vue-instantsearch). Thanks!

**Comment by pix2D** [comment] 2019-10-08 09:05
Can you clarify which algoliasearch-helper functions you mean?

The problem is I want to do the UI in 1 list. I don't want 2 separate lists for inclusion / exclusion (because then we have to double all our filters and there are quite a few).

So the UI is basically a standard searchable refinement list, then when a single item is refined an additional little toggle shows to "switch" that item from inclusion to exclusion (in Algolia terms this would be 2 actions -- first remove the refinement with the normal value, and then add it with the negative value).

How far I got is basically similar to the last sandbox posted above, but just implemented a little differently. It works in so far as both inclusions and exclusions are applying, but everything is in a OR relationship, and I need for there to be a AND between the inclusions and exclusions. So I'm wondering if there is a way for me to keep the RefinementList refines, and just add my own exclusions on top of that (and separated with a AND).

I saw [this](https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/in-depth/combining-boolean-operators/) example here which would seem to be able to do my logic, but I guess I'd need make my own custom RefinementList component then?

**Comment by Haroenv** [comment] 2019-10-08 12:18
So to be clear, I meant copying the connectRefinementList connector, and using these functions: https://community.algolia.com/algoliasearch-helper-js/reference.html#facet-exclusions

If this doesn't fit your use case, an alternative can be to not use the helper functions at all, and computing the filters string to send manually, and applying it with `addQueryParameter('filter', xxx)`
