### ISSUE TITLE
Can we remove Lodash from bundle?

### ISSUE THREAD

**Issue by mazipan** [algolia/vue-instantsearch#602] opened 2019-01-14 11:15 UTC
**Bundling without full Lodash**

If we see BundlePhobia (https://bundlephobia.com/result?p=vue-instantsearch@1.7.0), we can see that 33% of file size coming from Lodash and only 20% from codebase.

Thanks

**Comment by Haroenv** [comment] 2019-01-14 11:35
It's not possible to remove it directly, but it's an incremental project we are doing during this year. The problem is that one of our own dependencies (called algoliasearch-helper) is using lodash in a lot of places, most of which hard to replace.

Main issue: https://github.com/algolia/algoliasearch-helper-js/issues/617

I'll close this issue since there isn't much that can be done immediately, but we are aware of the issue. If you want to help, pull requests are of course encouraged!

**Closed by Haroenv** 2019-01-14 11:35 UTC
