### ISSUE TITLE
SortBy applies query parameters to my url

### ISSUE THREAD

**Issue by bootsmann1995** [algolia/vue-instantsearch#1005] opened 2021-06-24 10:56 UTC
**Bug 🐞**

### What is the current behavior?

AisSortBy adds query parameters to my url after load  in  my  nuxt.

https://www.a-hjort.dk/alle-produkter/?sortBy=AHjort%20Products%20da-DK

### What is the expected behavior?
I want this to be a clean url without any query parameters.

if I remove ais-sort-by from my vue file, it doesn't apply these query parameters. And if I select another value in sort-by and then switch back to the before selected value, it gives me the expected clean url.

I have checked that the index on my instance is the same as the selected index on sort-by when loaded. and they are the same.

**Comment by Haroenv** [comment] 2021-06-24 12:33
I've tried reproducing this in a sandbox, but it doesn't happen there: https://codesandbox.io/s/sweet-blackwell-rpx04?file=/src/App.vue.

Your application is in production mode, so I can't inspect it properly using for example vue devtools.

Is there any settings you have that are different than the ones I used in the sandbox? Could you edit it to show the issue?

**Comment by bootsmann1995** [comment] 2021-06-24 12:48
@Haroenv  okay i'll try to make a replica of how we do :) with nuxt routing and stuff

**Comment by bootsmann1995** [comment] 2021-06-24 12:49
@Haroenv this is not nuxt ssr with a nuxt router

**Comment by Haroenv** [comment] 2021-06-24 12:58
It shouldn't matter what kind of router is used, as the sortBy isn't in the result of stateMapping (which is the same one as used on your site). Could you edit it?

**Comment by bootsmann1995** [comment] 2021-06-24 13:00
Yes does it have any difference in how the router is defined in intialize? 

we use this: 

```  routing: {
                router: nuxtRouter(this.$router),
                stateMapping:  singleIndex(process.env.indice),
            },
            
```

The nuxtRouter part is a copy paste from this url: 
https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/vue/#combining-with-nuxtjs

from section 6

**Comment by Haroenv** [comment] 2021-06-24 15:27
no, that doesn't make a difference, since in the example I used, sortBy isn't present

**Comment by bootsmann1995** [comment] 2021-06-25 12:39
But algolia is not even configured like how you do in nuxt? :) could you make a code sandbox like this  in your nuxt template ? Afterwards can I make the mark-up and stuff like in my project, so we can reproduce the problem.

**Comment by bootsmann1995** [comment] 2021-06-25 12:48
this is similar to what we have https://codesandbox.io/s/interesting-fermi-rnotx?file=/src/App.vue

**Comment by Haroenv** [comment] 2021-06-25 14:03
I would have preferred if you actually made a sandbox that worked so the bug could be seen, but indeed, once it's in nuxt, the sortBy somehow gets added to the URL: https://codesandbox.io/s/crazy-germain-6zx0o?file=/pages/search.vue

**Comment by Haroenv** [comment] 2021-06-28 09:30
I've found the root cause, essentially in server side rendering (unrelated to vue router), we will read the ui state of all widgets, including the default value of sort by. Then it gets written to the router, since the default index is in ui state. 

In https://github.com/algolia/instantsearch.js/pull/4798 I fix the issue, by making sure the default index is never returned in the ui state. You can try out the fix by installing the codesandbox version in the linked pull request

Thanks for reporting this issue @bootsmann1995 !

**Comment by bootsmann1995** [comment] 2021-06-28 10:04
@Haroenv  Sounds cool! I'm not sure how to apply this fix to our solution :) but it seems as this wil be fixed in the next release of vue-instantsearch ?

**Comment by Haroenv** [comment] 2021-06-28 13:15
If you install InstantSearch with the codesandbox link in the PR, you will have the fix, in the next release of InstantSearch.js it will be as well, once it's merged, then you can install again on your project to use the default InstantSearch version

**Comment by bootsmann1995** [comment] 2021-06-28 13:19
Okay perfect, you can close the issue then.

**Closed** 2021-06-29 08:05 UTC
